export const CHANGE_MENU_DRAWER_STATE = "CHANGE_MENU_DRAWER_STATE";
export const INITIALIZE_APPLICATION_REQUEST = 'INITIALIZE_APPLICATION_REQUEST';
export const INITIALIZE_APPLICATION_REQUESTED = 'INITIALIZE_APPLICATION_REQUESTED';
export const INITIALIZE_APPLICATION_RESPONSE = 'INITIALIZE_APPLICATION_RESPONSE';
export const INITIALIZED_APPLICATION = 'INITIALIZED_APPLICATION';