export const CLIENTS_RECEIVED = 'CLIENTS_RECEIVED';
export const CLIENTS_REQUEST = 'CLIENTS_REQUEST';
export const CLIENT_DETAILS_RECEIVED = 'CLIENT_DETAILS_RECEIVED';
export const CLIENT_ACCOUNT_SUMMARIES_RECEIVED = 'CLIENT_ACCOUNT_SUMMARIES_RECEIVED';
export const CLIENT_ACCOUNT_SUMMARIES_REQUESTED = 'CLIENT_ACCOUNT_SUMMARIES_REQUESTED';
export const CLIENT_DETAILS_REQUESTED = 'CLIENT_DETAILS_REQUESTED';
export const CLIENT_TRANSACTIONS_REQUESTED = 'CLIENT_TRANSACTIONS_REQUESTED';
export const CLIENT_TRANSACTIONS_RECEIVED = 'CLIENT_TRANSACTIONS_RECEIVED';